config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "restaurants#index"
  get "restaurants/:id/willSplit", to: "restaurants#willSplit", as: "restaurants_will_split"
  get "restaurants/:id/willNotSplit", to: "restaurants#willNotSplit", as: "restaurants_will_not_split"
  get "restaurants/:id/favorite", to: "restaurants#favorite", as: "restaurants_favorite"
  get "restaurants/:id/comment", to: "restaurants#comment", as: "restaurants_comment"
  get "restaurants/:id/comment_add", to: "restaurants#addComment", as: "restaurants_comment_add"
  get "restaurants/profile", to: "restaurants#profile", as: "restaurants_profile"
  resources :restaurants, except: [:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  validates :user, uniqueness: { scope: :restaurant }

  belongs_to :user
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  after_initialize :set_defaults

  def set_defaults
    countWillSplit = 0
    countWillNotSplit = 0
  end

  # :countWillSplit, :countWillNotSplit,
  validates :name, :location, presence: true
  #validates_numericality_of :countWillSplit, :countWillNotSplit, :greater_than => -1
  has_many :votes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :votes
  has_many :favorites
  has_many :comments
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[ show edit update destroy ]

  # GET /restaurants or /restaurants.json
  def index

    if ((params[:name].nil? or params[:name] == "") and (params[:location].nil? or params[:location] == ""))
        @restaurants = Restaurant.all
        logger.info("all")
      elsif (!params[:location].nil? and (params[:name].nil? or params[:name] == ""))
        @restaurants = Restaurant.where(location: params[:location])
        logger.info("location only search")
        logger.info(params[:name])
        logger.info(params[:location])
      elsif (!params[:name].nil? and (params[:location].nil? or params[:location] == ""))
        @restaurants = Restaurant.where(name: params[:name])
        logger.info("name only search")
        logger.info(params[:name])
        logger.info(params[:location])
      else
        @restaurants = Restaurant.where(name: params[:name], location: params[:location])
        logger.info("both")
        logger.info(params[:name])
        logger.info(params[:location])
    end
  end

  def willSplit
    if (!user_signed_in?)
      redirect_to(new_user_registration_path)
    else
      @vote = current_user.votes.new(restaurant_id: params[:id], willSplit: true)
      @vote.save

    set_restaurant

    @restaurant.countWillSplit = Vote.where(restaurant: @restaurant, willSplit: true).count
    @restaurant.save

    redirect_to(restaurants_url)
    end
  end

  def willNotSplit
    if (!user_signed_in?)
      redirect_to(new_user_registration_path)
    else
    set_restaurant

    @vote = current_user.votes.new(restaurant_id: params[:id], willSplit: false)
    @vote.save

    @restaurant.countWillNotSplit = Vote.where(restaurant: @restaurant, willSplit: false).count
    @restaurant.save

    redirect_to(restaurants_url)
    end
  end

  def favorite
    if (!user_signed_in?)
      redirect_to(new_user_registration_path)
    else
    set_restaurant

    @favorite = current_user.favorites.new(restaurant_id: params[:id])
    @favorite.save

    redirect_to(restaurants_url)
    end
  end

  # GET /restaurants/1 or /restaurants/1.json
  def show
  end

  def comment
    set_restaurant
    @comments = Comment.where(restaurant: @restaurant).reverse_order
  end

  def addComment
    if (!user_signed_in?)
      redirect_to(new_user_registration_path)
    else
      set_restaurant
      @comment = current_user.comments.new(restaurant_id: params[:id], commentText: params[:commentText])
      @comment.save
      redirect_to(restaurants_comment_path)
    end

  end

  def profile
    if (!user_signed_in?)
      redirect_to(new_user_registration_path)
    else
    #@restaurants = Vote.where(user: current_user).restaurant
    @votes = Vote.where(user: current_user).reverse_order
    @favorites = Favorite.where(user: current_user).reverse_order
    @comments = Comment.where(user: current_user).reverse_order
  end
  end

  # GET /restaurants/new
  def new
    if (!user_signed_in?)
      redirect_to(new_user_registration_path)
    end
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
    if (!user_signed_in?)
      redirect_to(new_user_registration_path)
    else
    end
  end

  # POST /restaurants or /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)
    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to restaurant_url(@restaurant), notice: "Restaurant was successfully created." }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1 or /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to restaurant_url(@restaurant), notice: "Restaurant was successfully updated." }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1 or /restaurants/1.json
  def destroy
    @restaurant.destroy

    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: "Restaurant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :location, :countWillSplit, :countWillNotSplit)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>SprintOne</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      <%= link_to "Profile", restaurants_profile_path %>
      <p><%= current_user.email %></p>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path %>
      <%= link_to "Sign In", new_user_session_path %>
    <% end %>



    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
        <% restaurant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label "Count Will Split" %>
    <%= form.number_field :countWillSplit %>
  </div>

  <div class="field">
    <%= form.label "Count Will Not Split" %>
    <%= form.number_field :countWillNotSplit %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/_form_edit.html.erb
<%= form_with(model: restaurant) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
        <% restaurant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/comment.html.erb
<p id="notice"><%= notice %></p>

<header>
  <h1>Check Split Check</h1>
</header>

<%= form_with url: request.original_url + "_add", method: :get do |form| %>
  <h3>New Comment</h3>
  <%= form.text_field :commentText %>
  <%= form.submit "Add" %>
<% end %>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>

<table>
  <% @comments.each do |comment| %>
    <tr>
      <td><%= comment.created_at %></td>
      <td>Comment: </td>
      <td><%= comment.commentText %></td>
      <td>Commented by: </td>
      <td><%= comment.user.email %></td>
    </tr>
  <% end %>
</table>

app/views/restaurants/edit.html.erb
<header>
  <h1>Check Split Check</h1>
</header>

<h1>Editing Restaurant</h1>

<%= render 'form_edit', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<header>
  <h1>Check Split Check</h1>
</header>

<h1>Restaurants</h1>

<%= form_with url: "/restaurants", method: :get do |form| %>
  <h3>Name</h3>
  <%= form.text_field :name %>
  <h3>Location</h3>
  <%= form.text_field :location %>
  <%= form.submit "Search" %>
<% end %>
<%= link_to 'Add Restaurant', new_restaurant_path %>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th>Name &nbsp &nbsp</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= link_to 'Will Split', restaurants_will_split_path(restaurant) %></td>
        <td><%= restaurant.countWillSplit %></td>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.location %></td>
        <td><%= restaurant.countWillNotSplit %></td>
        <td><%= link_to 'Will Not Split', restaurants_will_not_split_path(restaurant) %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <% if Favorite.where(user: current_user, restaurant: restaurant).count == 0 %>
        <td><%= link_to 'Favorite', restaurants_favorite_path(restaurant) %></td>
        <% end %>
        <td><%= link_to 'Comments', restaurants_comment_path(restaurant) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/restaurants/new.html.erb
<header>
  <h1>Check Split Check</h1>
</header>

<h1>New Restaurant</h1>

<%= render 'form_edit', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/profile.html.erb
<p id="notice"><%= notice %></p>

<header>
  <h1>Check Split Check</h1>
</header>

<h1><%= current_user.email %></h1>
<%= link_to 'Back', restaurants_path %>
<div class="row">
        <div class="column">
          <h2>Votes</h2>
          <table>
          <thead>
            <tr>
              <th>Restaurant &nbsp &nbsp</th>
              <th>Vote</th>
              <th colspan="3"></th>
            </tr>
          </thead>

            <% @votes.each do |vote| %>
              <tr>
                <td><%= vote.restaurant.name %></td>
                <% if vote.willSplit %>
                <td>will split</td>
                <% else %>
                <td>will not split</td>
                <% end %>
              </tr>
            <% end %>
          </table>

        </div>
        <div class="column">
            <h2>Favorites</h2>
            <table>
            <thead>
              <tr>
                <th>Restaurant &nbsp &nbsp</th>
                <th>Location</th>
                <th colspan="3"></th>
              </tr>
            </thead>

              <% @favorites.each do |favorite| %>

                <tr>
                  <td><%= favorite.restaurant.name %></td>
                  <td><%= favorite.restaurant.location %></td>
                </tr>
              <% end %>
            </table>
        </div>
        <div class="column">
          <h2>Comments</h2>

          <table>
            <thead>
              <tr>
                <th>Restaurant &nbsp &nbsp</th>
                <th>Comment</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <% @comments.each do |comment| %>
              <tr>
                <td><%= comment.restaurant.name %></td>
                <td class="userMessage"><%= comment.commentText %></td>
              </tr>
            <% end %>
          </table>

        </div>
    </div>
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<header>
  <h1>Check Split Check</h1>
</header>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @restaurant.location %>
</p>

<p>
  <strong>Countwillsplit:</strong>
  <%= @restaurant.countWillSplit %>
</p>

<p>
  <strong>Countwillnotsplit:</strong>
  <%= @restaurant.countWillNotSplit %>
</p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>